wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.6
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723653014
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 98
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 98
      3:
      - 23
      4: 3.10.14
      5: 0.17.6
      6: 4.43.3
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 5.0e-07
batch_size:
  desc: null
  value: 4
train_epochs:
  desc: null
  value: 1000
model_name:
  desc: null
  value: SG161222/Realistic_Vision_V6.0_B1_noVAE
resolution:
  desc: null
  value: 512
